### PR TITLE
 Fix nuget dependencies.

### PR DESCRIPTION
**Pull request by the4ups**

### CODE REVIEW

**Comment by bradymholt** [comment]
@thechups Thanks for the PR - are you intentionally removing `dbup-consolescripts` from the dependencies?

**Comment by the4ups** [comment]
My bad.. dbup-consolescripts should be in dependencies..

**Comment by bradymholt** [comment]
Thanks for the PR.  I will merge.  Are you planning on submitting other changes?  If so, please let me know and I'll hold off releasing to NuGet.

**Comment by the4ups** [comment]
For now i haven`t another changes. So you can publish to nuget.
Thank you

**Comment by bradymholt** [comment]
Thanks - published: https://www.nuget.org/packages/dbup-sqlserver-scripting/1.6.2

**Pull request merged**
