### PR TITLE
 Using "DateLastModified" to select objects to generate definintions.

### PR DESCRIPTION
**Pull request by the4ups**
When migration script modify objects with stored procedures, or migration script modify index on table regexp useless to select objects to generate definitions. So i change logic to use "DateLastModified" column to check when object modified. Now there are two approaches: 
1. var scripter = new DbObjectScripter(ConnectionString, m_options, Log);
    scripter.ScriptAll();
- this approach will use DateTime.MinValue as filter for DateLastModified and script all objects.

2. var scripter = new DbObjectScripter(ConnectionString, m_options, Log);
   scripter.StartWatch(); // here we get sysdatetime from server
   result = m_engine.PerformUpgrade();
   scripter.ScriptWatched(); // script objects where  "DateLastModified" > saved sysdatetime

### CODE REVIEW

**Comment by bradymholt** [comment]
Thanks for the PR.  Can you undo the formatting changes in this PR?  I'd prefer to keep the formatting as-is and also this will help me clearly see the diff.

**Comment by the4ups** [comment]
Ok, need some time for this.

**Comment by the4ups** [comment]
Done.

**Comment by bradymholt** [comment]
I apologize but after reviewing these changes more I would rather keep the current implementation for simplicity.  Feel free to use what you have from your own branch.  I do appreciate your involvement however!

**Pull request closed without merging**
